// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RacingCoach.Infrastructure.Persistence;

#nullable disable

namespace RacingCoach.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260802120000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("RacingCoach.Domain.Models.Sessions.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndTime");

                    b.HasIndex("StartTime");

                    b.ToTable("GameSessions", (string)null);
                });

            modelBuilder.Entity("RacingCoach.Infrastructure.Persistence.Entities.DbTelemetryData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AccelerationX")
                        .HasColumnType("REAL");

                    b.Property<double>("AccelerationY")
                        .HasColumnType("REAL");

                    b.Property<double>("AccelerationZ")
                        .HasColumnType("REAL");

                    b.Property<double>("Brake")
                        .HasColumnType("REAL");

                    b.Property<double>("BrakeTempFL")
                        .HasColumnType("REAL");

                    b.Property<double>("BrakeTempFR")
                        .HasColumnType("REAL");

                    b.Property<double>("BrakeTempRL")
                        .HasColumnType("REAL");

                    b.Property<double>("BrakeTempRR")
                        .HasColumnType("REAL");

                    b.Property<int>("CurrentLap")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FuelCapacity")
                        .HasColumnType("REAL");

                    b.Property<double>("FuelLevel")
                        .HasColumnType("REAL");

                    b.Property<byte>("Gear")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PositionX")
                        .HasColumnType("REAL");

                    b.Property<double>("PositionY")
                        .HasColumnType("REAL");

                    b.Property<double>("PositionZ")
                        .HasColumnType("REAL");

                    b.Property<double>("RPM")
                        .HasColumnType("REAL");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Speed")
                        .HasColumnType("REAL");

                    b.Property<double>("Steering")
                        .HasColumnType("REAL");

                    b.Property<double>("SuspensionFL")
                        .HasColumnType("REAL");

                    b.Property<double>("SuspensionFR")
                        .HasColumnType("REAL");

                    b.Property<double>("SuspensionRL")
                        .HasColumnType("REAL");

                    b.Property<double>("SuspensionRR")
                        .HasColumnType("REAL");

                    b.Property<double>("Throttle")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalLaps")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TireTempFL")
                        .HasColumnType("REAL");

                    b.Property<double>("TireTempFR")
                        .HasColumnType("REAL");

                    b.Property<double>("TireTempRL")
                        .HasColumnType("REAL");

                    b.Property<double>("TireTempRR")
                        .HasColumnType("REAL");

                    b.Property<double>("VelocityX")
                        .HasColumnType("REAL");

                    b.Property<double>("VelocityY")
                        .HasColumnType("REAL");

                    b.Property<double>("VelocityZ")
                        .HasColumnType("REAL");

                    b.Property<int>("Sector")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("Timestamp");

                    b.ToTable("TelemetryData", (string)null);
                });

            modelBuilder.Entity("RacingCoach.Infrastructure.Persistence.Entities.DbProviderConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("ProviderConfigurations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
